# sqllocks_spindle/verify/report.py
"""VerifyResult dataclass and VerifyReport renderer."""

from __future__ import annotations

import json
from dataclasses import dataclass, field

from sqllocks_spindle.validation.gates import GateResult


@dataclass
class VerifyResult:
    """Outcome of a spindle verify run."""

    passed: bool
    gate_results: list[GateResult]
    row_counts: dict[str, int]
    run_at: str               # ISO 8601
    data_path: str
    schema_path: str | None
    statistical: bool
    spindle_version: str


class VerifyReport:
    """Renders a VerifyResult as Markdown or JSON."""

    def __init__(self, result: VerifyResult) -> None:
        self._r = result

    def to_json(self, indent: int = 2) -> str:
        """Serialize result to a JSON string."""
        r = self._r
        payload = {
            "spindle_version": r.spindle_version,
            "run_at": r.run_at,
            "data_path": r.data_path,
            "schema_path": r.schema_path,
            "statistical": r.statistical,
            "passed": r.passed,
            "row_counts": r.row_counts,
            "gates": [
                {
                    "gate": gr.gate_name,
                    "passed": gr.passed,
                    "errors": gr.errors,
                    "warnings": gr.warnings,
                    "details": gr.details,
                }
                for gr in r.gate_results
            ],
        }
        return json.dumps(payload, indent=indent, default=str)

    def to_markdown(self) -> str:
        """Render result as a reproducible Markdown report."""
        r = self._r
        lines: list[str] = []

        overall = "PASS" if r.passed else "FAIL"
        banner = f"**Overall: {overall}**"

        lines += [
            "# Spindle Verify Report",
            "",
            f"**Generated:** {r.run_at}  ",
            f"**Data path:** {r.data_path}  ",
            f"**Schema:** {r.schema_path or '(none)'}  ",
            f"**Statistical tests:** {'Yes' if r.statistical else 'No'}  ",
            f"**Spindle version:** {r.spindle_version}  ",
            "",
            banner,
            "",
            "---",
            "",
            "## Summary",
            "",
            "| Gate | Status | Errors | Warnings |",
            "|------|--------|--------|----------|",
        ]

        for gr in r.gate_results:
            status = "PASS" if gr.passed else "FAIL"
            icon = "✅" if gr.passed else "❌"
            lines.append(
                f"| {gr.gate_name} | {icon} {status} | {len(gr.errors)} | {len(gr.warnings)} |"
            )

        total_errors = sum(len(gr.errors) for gr in r.gate_results)
        total_warnings = sum(len(gr.warnings) for gr in r.gate_results)
        lines += [
            "",
            f"**Total:** {len(r.gate_results)} gates — {total_errors} errors, {total_warnings} warnings",
        ]

        if r.row_counts:
            lines += ["", "## Row Counts", "", "| Table | Rows |", "|-------|------|"]
            for table, count in sorted(r.row_counts.items()):
                lines.append(f"| {table} | {count:,} |")

        has_findings = any(gr.errors or gr.warnings for gr in r.gate_results)
        if has_findings:
            lines += ["", "## Gate Details", ""]
            for gr in r.gate_results:
                if not gr.errors and not gr.warnings:
                    continue
                status = "PASS" if gr.passed else "FAIL"
                lines.append(f"### {gr.gate_name} — {status}")
                lines.append("")
                for e in gr.errors:
                    lines.append(f"- **ERROR:** {e}")
                for w in gr.warnings:
                    lines.append(f"- **WARN:** {w}")
                lines.append("")

        reproduce_cmd = f"spindle verify {r.data_path}"
        if r.schema_path:
            reproduce_cmd += f" --schema {r.schema_path}"
        if r.statistical:
            reproduce_cmd += " --statistical"

        lines += [
            "## Methodology",
            "",
            f"This report was generated by `spindle verify` v{r.spindle_version}.",
            "Gates applied:",
        ]
        gate_descriptions = {
            "schema_conformance": "Column names and types validated against schema declarations.",
            "null_constraint": "Non-nullable columns checked for null values.",
            "unique_constraint": "Primary key columns checked for duplicate values.",
            "referential_integrity": "FK column values verified against parent PK sets.",
            "distribution": (
                "KS test (numeric) and chi-squared test (enum) comparing observed "
                "distributions to schema-fitted parameters (α=0.05)."
            ),
        }
        for gr in r.gate_results:
            desc = gate_descriptions.get(gr.gate_name, "Custom gate.")
            lines.append(f"- **{gr.gate_name}:** {desc}")

        lines += [
            "",
            "**Reproduce this report:**",
            "",
            "```",
            reproduce_cmd,
            "```",
        ]

        return "\n".join(lines) + "\n"
