"""Entry point for multi-process chunked generation with multi-sink fan-out."""
from __future__ import annotations

import json
import logging
import os
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from typing import TYPE_CHECKING

import numpy as np

from sqllocks_spindle.engine.chunk_worker import generate_chunk
from sqllocks_spindle.engine.sink_registry import SinkRegistry

if TYPE_CHECKING:
    from sqllocks_spindle.engine.sinks.base import Sink

logger = logging.getLogger(__name__)

_WARN_RAM_FRACTION = 0.80  # warn when estimated working set exceeds this fraction of available RAM


class _SpindleJSONEncoder(json.JSONEncoder):
    """Extend the default JSON encoder to handle types generated by Spindle.

    Handles: numpy scalars, pandas Timestamps, numpy arrays, and Python None.
    """

    def default(self, o):
        import numpy as np
        try:
            import pandas as pd
            # NaT, NaN, NA — treat as null. Must come BEFORE Timestamp check
            # because pd.isna(NaT) returns True but NaT also isinstance Timestamp.
            if pd.isna(o):
                return None
            if isinstance(o, pd.Timestamp):
                return o.isoformat()
        except (ImportError, TypeError, ValueError):
            # pd.isna() can raise on certain types (arrays, dicts) — fall through
            pass
        if isinstance(o, np.integer):
            return int(o)
        if isinstance(o, np.floating):
            return float(o)
        if isinstance(o, np.bool_):
            return bool(o)
        if isinstance(o, np.ndarray):
            return o.tolist()
        return super().default(o)


def _classify_tables(
    schema_counts: dict[str, int],
    chunk_size: int,
) -> tuple[set[str], set[str]]:
    """Split tables into static (reference) and dynamic (fact) sets.

    Static tables have a schema-derived count strictly less than chunk_size.
    They are generated once with their natural cardinality and their data is
    broadcast to every chunk worker so FK resolution works across chunks.

    Dynamic tables have schema counts >= chunk_size.  They are generated
    chunk_size rows per chunk and concatenated by the sinks.
    """
    static: set[str] = set()
    dynamic: set[str] = set()
    for table_name, count in schema_counts.items():
        if count < chunk_size:
            static.add(table_name)
        else:
            dynamic.add(table_name)
    return static, dynamic


def _generate_static_tables(
    schema_path: str,
    static_tables: set[str],
    schema_counts: dict[str, int],
    seed: int,
    schema_dict: dict,
) -> dict[str, dict[str, list]]:
    """Generate static (reference) tables in the main process using Spindle.

    Static tables are generated once with their natural cardinality. The result
    is a plain-dict structure identical to generate_chunk output so sinks can
    consume it with the same write_chunk path.
    """
    import numpy as np
    from sqllocks_spindle.engine.generator import apply_compute_phase
    from sqllocks_spindle.engine.id_manager import IDManager
    from sqllocks_spindle.engine.strategies.base import StrategyRegistry
    from sqllocks_spindle.engine.strategies.computed import ComputedStrategy
    from sqllocks_spindle.engine.strategies.conditional import ConditionalStrategy
    from sqllocks_spindle.engine.strategies.correlated import CorrelatedStrategy
    from sqllocks_spindle.engine.strategies.derived import DerivedStrategy
    from sqllocks_spindle.engine.strategies.distribution import DistributionStrategy
    from sqllocks_spindle.engine.strategies.enum import WeightedEnumStrategy
    from sqllocks_spindle.engine.strategies.faker_strategy import FakerStrategy
    from sqllocks_spindle.engine.strategies.first_per_parent import FirstPerParentStrategy
    from sqllocks_spindle.engine.strategies.foreign_key import ForeignKeyStrategy
    from sqllocks_spindle.engine.strategies.formula import FormulaStrategy
    from sqllocks_spindle.engine.strategies.lifecycle import LifecycleStrategy
    from sqllocks_spindle.engine.strategies.lookup import LookupStrategy
    from sqllocks_spindle.engine.strategies.native import NativeStrategy
    from sqllocks_spindle.engine.strategies.pattern import PatternStrategy
    from sqllocks_spindle.engine.strategies.record_field import RecordFieldStrategy
    from sqllocks_spindle.engine.strategies.record_sample import RecordSampleStrategy
    from sqllocks_spindle.engine.strategies.reference_data import ReferenceDataStrategy
    from sqllocks_spindle.engine.strategies.scd2 import SCD2Strategy
    from sqllocks_spindle.engine.strategies.self_referencing import (
        SelfReferencingStrategy, SelfRefFieldStrategy,
    )
    from sqllocks_spindle.engine.strategies.sequence import SequenceStrategy
    from sqllocks_spindle.engine.strategies.temporal import TemporalStrategy
    from sqllocks_spindle.engine.strategies.uuid_strategy import UUIDStrategy
    from sqllocks_spindle.engine.strategies.composite_foreign_key import (
        CompositeForeignKeyStrategy, CompositeFKFieldStrategy,
    )
    from sqllocks_spindle.engine.table_generator import TableGenerator
    from sqllocks_spindle.schema.dependency import DependencyResolver
    from sqllocks_spindle.schema.parser import SchemaParser
    import pandas as pd

    schema = SchemaParser().parse_dict(schema_dict)

    registry = StrategyRegistry()
    registry.register("sequence", SequenceStrategy())
    registry.register("uuid", UUIDStrategy())
    registry.register("native", NativeStrategy())
    registry.register("faker", FakerStrategy())
    registry.register("weighted_enum", WeightedEnumStrategy())
    registry.register("distribution", DistributionStrategy())
    registry.register("temporal", TemporalStrategy())
    registry.register("formula", FormulaStrategy())
    registry.register("derived", DerivedStrategy())
    registry.register("correlated", CorrelatedStrategy())
    registry.register("foreign_key", ForeignKeyStrategy())
    registry.register("lookup", LookupStrategy())
    registry.register("reference_data", ReferenceDataStrategy())
    registry.register("pattern", PatternStrategy())
    registry.register("conditional", ConditionalStrategy())
    registry.register("computed", ComputedStrategy())
    registry.register("lifecycle", LifecycleStrategy())
    registry.register("self_referencing", SelfReferencingStrategy())
    registry.register("self_ref_field", SelfRefFieldStrategy())
    registry.register("first_per_parent", FirstPerParentStrategy())
    registry.register("record_sample", RecordSampleStrategy())
    registry.register("record_field", RecordFieldStrategy())
    registry.register("scd2", SCD2Strategy())
    registry.register("composite_foreign_key", CompositeForeignKeyStrategy())
    registry.register("composite_fk_field", CompositeFKFieldStrategy())
    registry.load_entrypoint_plugins()

    rng = np.random.default_rng(seed)
    id_manager = IDManager(rng)
    table_gen = TableGenerator(registry, id_manager)

    # Pre-register synthetic PK pools for dynamic tables so static tables that
    # FK against a dynamic parent can resolve their FKs at static-gen time.
    # Dynamic tables haven't been generated yet, but their sequence-based PKs
    # are deterministic (1..N), so a RangePKPool perfectly matches what the
    # chunk workers will produce.
    dynamic_set = set(schema_counts.keys()) - static_tables
    for _dt in dynamic_set:
        if _dt in schema.tables:
            id_manager.register_range(_dt, start=1, count=schema_counts[_dt])

    model_config: dict = {
        "locale": schema.model.locale,
        "date_range": schema.model.date_range,
        "seed": seed,
    }
    if "_domain_path" in schema_dict:
        model_config["_domain_path"] = schema_dict["_domain_path"]

    gen_order = DependencyResolver().resolve(schema)
    result_dfs: dict[str, pd.DataFrame] = {}

    # Walk the dependency graph in order. For each table:
    #   • static  → generate fully and add to result_dfs (returned to caller)
    #   • dynamic → generate a small sample (capped at DYNAMIC_SAMPLE_SIZE) and
    #     register column data with the IDManager so subsequent static tables
    #     that LookupStrategy/CorrelatedStrategy against this dynamic parent
    #     can resolve. Then re-register the synthetic full-range PK pool so FK
    #     lookups still see all N possible PKs (chunk workers will produce them).
    # The sample is NOT included in result_dfs — chunk workers generate the
    # full dynamic data and write it to sinks.
    DYNAMIC_SAMPLE_SIZE = 1000
    for table_name in gen_order:
        if table_name not in schema.tables:
            continue
        is_static = table_name in static_tables
        natural_count = schema_counts.get(table_name, 100)
        row_count = natural_count if is_static else min(DYNAMIC_SAMPLE_SIZE, natural_count)
        child_rng = np.random.default_rng(seed ^ (hash(table_name) & 0xFFFF_FFFF))
        try:
            df = table_gen.generate(
                table=schema.tables[table_name],
                row_count=row_count,
                rng=child_rng,
                model_config=model_config,
                schema=schema,
                sequence_offset=0,
            )
        except Exception as exc:
            if is_static:
                raise
            logger.warning(
                "Could not pre-sample dynamic table '%s': %s. Static tables "
                "that look up against it may fail.", table_name, exc,
            )
            continue

        if is_static:
            result_dfs[table_name] = df
        else:
            # Dynamic sample — register table data for downstream lookups,
            # then restore the synthetic full-range PK pool.
            pk_cols = list(schema.tables[table_name].primary_key or [])
            if pk_cols:
                id_manager.register_table(table_name, df, pk_cols)
                id_manager.register_range(
                    table_name, start=1, count=natural_count,
                )

    apply_compute_phase(result_dfs, schema)

    return {
        table_name: {
            col: (series.tolist() if hasattr(series, "tolist") else list(series))
            for col, series in df.items()
        }
        for table_name, df in result_dfs.items()
    }


class ScaleRouter:
    """Entry point for multi-process chunked generation with multi-sink fan-out.

    Args:
        schema_path: Path to a .json file containing a serialized SpindleSchema.
        sinks: List of Sink instances to receive generated data.
        chunk_size: Rows per chunk. Default 500_000.
        max_workers: Subprocess count. Default os.cpu_count() - 1. Capped
            automatically if the estimated working set would exceed 80 % of
            available RAM.
    """

    def __init__(
        self,
        schema_path: str,
        sinks: list[Sink],
        chunk_size: int = 500_000,
        max_workers: int | None = None,
    ) -> None:
        self._schema_path = schema_path
        self._registry = SinkRegistry(sinks)
        self._chunk_size = chunk_size
        requested = max_workers or max(1, (os.cpu_count() or 2) - 1)
        self._max_workers = self._cap_workers(requested, chunk_size)

    @staticmethod
    def _cap_workers(requested: int, chunk_size: int) -> int:
        """Cap worker count if estimated RAM working set would exceed 80 % of available."""
        try:
            import psutil
            available = psutil.virtual_memory().available
            # Rough estimate: 8 bytes/row × 10 columns per chunk
            bytes_per_chunk = chunk_size * 8 * 10
            max_by_ram = max(1, int(available * _WARN_RAM_FRACTION / bytes_per_chunk))
            if max_by_ram < requested:
                logger.warning(
                    "Capping max_workers from %d to %d to stay within 80%% of available RAM "
                    "(%.1f GB free, ~%.1f GB per chunk).",
                    requested, max_by_ram,
                    available / 1024 ** 3,
                    bytes_per_chunk / 1024 ** 3,
                )
                return max_by_ram
        except ImportError:
            pass
        return requested

    def run(
        self,
        total_rows: int,
        seed: int = 42,
    ) -> dict:
        """Generate total_rows rows and fan out to all sinks.

        Tables whose schema-derived row count is < chunk_size are treated as
        **static** (reference/dimension) tables: they are generated once with
        their natural cardinality and written to the sinks a single time.
        Their PK data is broadcast into every chunk worker so FK references
        resolve correctly without replication.

        Tables whose schema-derived row count >= chunk_size are **dynamic**
        (fact) tables: they are generated chunk_size rows per chunk across
        ceil(total_rows / chunk_size) chunks.

        Returns:
            Stats dict: rows_generated, elapsed_seconds, throughput_rows_per_sec,
            memory_peak_gb (estimated).
        """
        import json
        from pathlib import Path
        from sqllocks_spindle.schema.parser import SchemaParser
        from sqllocks_spindle.engine.generator import calculate_row_counts

        schema_dict = json.loads(Path(self._schema_path).read_text())
        parser = SchemaParser()
        schema = parser.parse_dict(schema_dict)

        # Classify tables
        schema_counts = calculate_row_counts(schema)
        static_tables, dynamic_tables = _classify_tables(schema_counts, self._chunk_size)

        logger.info(
            "ScaleRouter: %d static tables (generated once), %d dynamic tables (chunked)",
            len(static_tables), len(dynamic_tables),
        )
        if static_tables:
            logger.debug("Static: %s", sorted(static_tables))
        if dynamic_tables:
            logger.debug("Dynamic: %s", sorted(dynamic_tables))

        self._registry.open(schema)

        n_chunks = max(1, (total_rows + self._chunk_size - 1) // self._chunk_size)
        rows_generated = 0
        start = time.perf_counter()

        # --- Step 1: generate static tables once and broadcast their PK data ---
        static_pk_data: dict[str, dict[str, list]] = {}
        if static_tables:
            static_chunk = _generate_static_tables(
                schema_path=self._schema_path,
                static_tables=static_tables,
                schema_counts=schema_counts,
                seed=seed,
                schema_dict=schema_dict,
            )
            # Write static tables to sinks exactly once
            for table_name, col_lists in static_chunk.items():
                arrays = {col: np.array(vals) for col, vals in col_lists.items()}
                self._registry.write_chunk(table_name, arrays)
            static_pk_data = static_chunk
            logger.info("Static tables written to sinks.")

        # Embed static PK data and metadata into schema_dict for subprocess workers
        schema_dict["_static_tables"] = list(static_tables)
        schema_dict["_static_pk_data"] = static_pk_data
        schema_dict["_dynamic_tables"] = list(dynamic_tables)
        schema_dict["_schema_counts"] = schema_counts
        schema_dict["_base_seed"] = seed

        # Write augmented schema_dict back so subprocess workers pick it up.
        # Use _SpindleJSONEncoder to handle Timestamps and numpy scalars that
        # may appear in static_pk_data column values.
        import tempfile
        tmp_schema_file = tempfile.NamedTemporaryFile(
            suffix=".json", mode="w", delete=False
        )
        try:
            json.dump(schema_dict, tmp_schema_file, cls=_SpindleJSONEncoder)
            tmp_schema_file.close()
            augmented_schema_path = tmp_schema_file.name

            # --- Step 2: generate dynamic tables in parallel chunks ---
            try:
                with ProcessPoolExecutor(max_workers=min(self._max_workers, n_chunks)) as pool:
                    futures = {}
                    for i in range(n_chunks):
                        chunk_offset = i * self._chunk_size
                        chunk_count = min(self._chunk_size, total_rows - chunk_offset)
                        chunk_seed = seed ^ i
                        fut = pool.submit(
                            generate_chunk,
                            augmented_schema_path,
                            chunk_seed,
                            chunk_offset,
                            chunk_count,
                        )
                        futures[fut] = (i, chunk_count)

                    for future in as_completed(futures):
                        chunk_idx, chunk_count = futures[future]
                        chunk_data = future.result()

                        for table_name, col_lists in chunk_data.items():
                            arrays = {col: np.array(vals) for col, vals in col_lists.items()}
                            self._registry.write_chunk(table_name, arrays)

                        rows_generated += chunk_count
                        logger.info(
                            "Chunk %d/%d done — %s dynamic rows written",
                            chunk_idx + 1, n_chunks, f"{rows_generated:,}",
                        )
            finally:
                self._registry.close()
        finally:
            import os as _os
            if _os.path.exists(tmp_schema_file.name):
                _os.unlink(tmp_schema_file.name)

        elapsed = time.perf_counter() - start
        return {
            "rows_generated": rows_generated,
            "elapsed_seconds": round(elapsed, 2),
            "throughput_rows_per_sec": int(rows_generated / max(elapsed, 0.001)),
            "memory_peak_gb": self._estimate_peak_gb(),
        }

    def _estimate_peak_gb(self) -> float:
        try:
            import psutil
            proc = psutil.Process(os.getpid())
            return round(proc.memory_info().rss / 1024 ** 3, 2)
        except ImportError:
            return 0.0
